### ISSUE TITLE
build-administration.sh fails with npm error ELIFECYCLE 137

### ISSUE THREAD

**Issue by ts-mothership** [shopware/shopware#1617]
**Description**  
We have a web server (1 CPU, 2 GB memory) and trying to build the administration via bin/build-administration.sh command:
```
$ bin/build-administration.sh


 [OK] Dumped plugin configuration.


npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.13 install /var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js


Skipping 'fsevents' build as platform linux is not supported

> ejs@2.7.4 postinstall /var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> fsevents@1.2.13 install /var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js


Skipping 'fsevents' build as platform linux is not supported

> node-sass@4.14.1 install /var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration/node_modules/node-sass
> node scripts/install.js

Cached binary found at /var/www/share/.npm/_cacache/node-sass/4.14.1/linux-x64-72_binding.node

> node-sass@4.14.1 postinstall /var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration/node_modules/node-sass
> node scripts/build.js

Binary found at /var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration/node_modules/node-sass/vendor/linux-x64-72/binding.node
Testing binary
Binary is fine

> core-js@2.6.11 postinstall /var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.11 postinstall /var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration/node_modules/babel-register/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall /var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

added 2156 packages in 19.141s

> administration@1.0.0 build /var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration
> mode=production webpack

# Compiling with Webpack configuration
# Production mode is activated 🚀
# Plugin "Storefront": Injected successfully
# Plugin "SwagShopwarePwa": Injected successfully
# Plugin "SwagMarkets": Injected successfully

Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! administration@1.0.0 build: `mode=production webpack`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the administration@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/share/.npm/_logs/2021-01-25T08_40_33_091Z-debug.log
```

On our web server there is PHP, MySQL, Nginx, npm running, but still ~1GB RAM is available. We can observe, that npm uses all the memory and as soon as remaining memory hits 0, the command fails.

**Possible Solution**  
Either:
- Try to reduce memory consumption, IMHO should not exceed 512MB
- List npm system requirements in https://docs.shopware.com/en/shopware-platform-dev-en/system-guide/system-requirements?category=shopware-platform-dev-en/system-guide

**Additional context**  
2021-01-25T08_40_33_091Z-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   '--prefix',
1 verbose cli   '/var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration/',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.20.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle administration@1.0.0~prebuild: administration@1.0.0
6 info lifecycle administration@1.0.0~build: administration@1.0.0
7 verbose lifecycle administration@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle administration@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration/node_modules/.bin:~/.composer/vendor/bin:/var/www/share/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle administration@1.0.0~build: CWD: /var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration
10 silly lifecycle administration@1.0.0~build: Args: [ '-c', 'mode=production webpack' ]
11 silly lifecycle administration@1.0.0~build: Returned: code: 137  signal: null
12 info lifecycle administration@1.0.0~build: Failed to exec build script
13 verbose stack Error: administration@1.0.0 build: `mode=production webpack`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid administration@1.0.0
15 verbose cwd /var/www/share/<domain-redacted>/htdocs.d/2/www
16 verbose Linux 4.15.0
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "--prefix" "/var/www/share/<domain-redacted>/htdocs.d/2/www/vendor/shopware/administration/Resources/app/administration/" "build"
18 verbose node v12.20.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 137
22 error administration@1.0.0 build: `mode=production webpack`
22 error Exit status 137
23 error Failed at the administration@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

**Comment by shyim** [comment]
You need more memory to built the administration

**Comment by ts-mothership** [comment]
@shyim Can you please document the amount of memory needed to build the administration?

As our background: more memory costs more money. we need to communicate the additional costs to our partners.

**Comment by andreasemer** [comment]
@shyim Have you looked in the trace of the process and have you really debugged it? 

In a sustainable world it's maybe not the best idea to just throw hardware against a problem. SW is used by a large number of vendors, the accumulated RAM is not to be underestimated.

**Comment by shyim** [comment]
First you should never build on a production system the administration. This should happen in a CI and the build should be then deployed.  
On my machine the process takes ~1,1GB memory. When you already have some stuff running you will hit it really fast

@andreasemer 
You need to build the administration only when you develop plugins for the administration. For the normal usage is this not needed
