### ISSUE TITLE
npm-sass / gyp errors when running ./psh.phar install on ubuntu 16.04

### ISSUE THREAD

**Issue by BogdanChayka** [shopware/shopware#234]
`    gyp ERR! System Linux 4.15.0-1044-gcp
        gyp ERR! command "/usr/bin/node" "/app/platform/src/Storefront/Resources/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose
" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd /app/platform/src/Storefront/Resources/node_modules/node-sass
        gyp ERR! node -v v11.15.0
        gyp ERR! node-gyp -v v3.8.0
        gyp ERR! not ok 
        Build failed with error code: 1
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the node-sass@4.12.0 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

` Unable to save binary /app/platform/src/Administration/Resources/administration/node_modules/node-sass/vendor/linux-x64-67 : { Error
: EACCES: permission denied, mkdir '/app/platform/src/Administration/Resources/administration/node_modules/node-sass/vendor'
            at Object.mkdirSync (fs.js:773:3)
            at sync (/app/platform/src/Administration/Resources/administration/node_modules/mkdirp/index.js:71:13)
            at Function.sync (/app/platform/src/Administration/Resources/administration/node_modules/mkdirp/index.js:77:24)
            at checkAndDownloadBinary (/app/platform/src/Administration/Resources/administration/node_modules/node-sass/scripts/install.js:1
14:11)
            at Object.<anonymous> (/app/platform/src/Administration/Resources/administration/node_modules/node-sass/scripts/install.js:157:1
)
            at Module._compile (internal/modules/cjs/loader.js:816:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
            at Module.load (internal/modules/cjs/loader.js:685:32)
            at Function.Module._load (internal/modules/cjs/loader.js:620:12)
            at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
          errno: -13,
          syscall: 'mkdir',
          code: 'EACCES',
          path:`

**Comment by BogdanChayka** [comment]
`npm install -g npm@latest`

helped with it, those issues happen with npm version 6.10 that comes with the docker setup, 6.11 works fine!

**Comment by BogdanChayka** [comment]
`sudo npm install --unsafe-perm` for some reason also helps, why do i need unsafe permissions to simply install packages without errors?

**Comment by BogdanChayka** [comment]
Ok so I could reproduce this issue, when you run bin/setup the first time, and then have to rerun it, you might encounter permission errors on linux, after i did sudo chown -R $USER:$USER /project/location it went through to "All commands successfully executed!" :)

**Comment by pantrtxp** [comment]
Since you resolved the Error yourself I close this due to inactivity.
