### ISSUE TITLE
Installing shopware on Mac: Stuck on (25/40) Starting > npm clean-install --prefix vendor/shopware/platform/src/Administration/Resources

### ISSUE THREAD

**Issue by SannePetersNL** [shopware/shopware#334]
Hello, I'm following your guide (https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/system-installation-guides/mac-os-x#install-npm-node) to install Shopware on Mac using MAMP.

At the 'Start Shopware 6 setup' paragraph the command crashes with the following message:

`(25/40) Starting
> npm clean-install --prefix vendor/shopware/platform/src/Administration/Resources

	Usage: npm <command>

	where <command> is one of:
	    access, adduser, audit, bin, bugs, c, cache, ci, cit,
	    completion, config, create, ddp, dedupe, deprecate,
	    dist-tag, docs, doctor, edit, explore, get, help,
	    help-search, hook, i, init, install, install-test, it, link,
	    list, ln, login, logout, ls, outdated, owner, pack, ping,
	    prefix, profile, prune, publish, rb, rebuild, repo, restart,
	    root, run, run-script, s, se, search, set, shrinkwrap, star,
	    stars, start, stop, t, team, test, token, tst, un,
	    uninstall, unpublish, unstar, up, update, v, version, view,
	    whoami

	npm <command> -h  quick help on <command>
	npm -l            display full usage info
	npm help <term>   search for help on <term>
	npm help npm      involved overview

	Specify configs in the ini-formatted file:
	    /Users/sannepeters/.npmrc
	or on the command line via: npm <command> --key value
	Config info can be viewed via: npm help config

	npm@6.4.1 /usr/local/Cellar/node@8/8.16.2/lib/node_modules/npm

	Did you mean one of these?
	    uninstall
	    install

Execution aborted, a subcommand failed!`

I downgraded Node because that was where it crashed before this.

Node: v8.16.2
NPM: 6.4.1
PHP: 7.2.21

Any idea's? Thanks in advance :)

**Comment by keulinho** [comment]
The `npm clean-install` comand is available since NPM 6.5, try upgrading your NPM version.

Kind regards
Jonas

**Comment by SannePetersNL** [comment]
@keulinho  Ah thanks that was the problem indeed. 

I got the install script working now and I can view the front-end in the browser. But when i go to the back-end I get a white page. See: https://imgur.com/a/QR9im4J

In the console I get the following error:

`admin:57 Uncaught ReferenceError: Shopware is not defined
    at admin:57`

Which gives the following error in the file: https://imgur.com/a/QR9im4J

In the front-end I do get products and everything.

Anyone have an idea? Thanks in advance.

**Comment by SannePetersNL** [comment]
Ah I needed to copy paste the administration map from the setup. Now I got a fav icon but still an error. 

`Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Function.value (commons.js:1)
    at e.value (commons.js:1)
    at e.value (commons.js:1)
    at admin:57`

https://imgur.com/a/QR9im4J

**Comment by keulinho** [comment]
Could you try running `./psh.phar administration:build`?
Does this return any errors?

**Comment by SannePetersNL** [comment]
Yes, they start under 2/3

'Building project for production...'

`(node:43671) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
	parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
	[ './src/module/sw-cms/blocks/image/image-three-cover/component/sw-cms-block-image-three-cover.scss (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--15-2!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/module/sw-cms/blocks/image/image-three-cover/component/sw-cms-block-image-three-cover.scss)\nModule build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):\nModuleBuildError: Module build failed (from ./node_modules/sass-loader/libHash: 478b115c43d79cb7db12
	Version: webpack 4.38.0
	Time: 61458ms
	Built at: 12/03/2019 2:06:49 PM
	                         Asset      Size        Chunks  Chunk Names
	04a704910b9a8cb8e86e.worker.js  58.3 KiB
	            static/css/app.css   0 bytes           app  app
	   static/css/vendors-node.css  15.2 KiB  vendors-node  vendors-node
	              static/js/app.js  5.16 MiB           app  app
	          static/js/commons.js   158 KiB       commons  commons
	          static/js/runtime.js  1.45 KiB       runtime  runtime
	       static/js/storefront.js   101 KiB    storefront  storefront
	     static/js/vendors-node.js   1.3 MiB  vendors-node  vendors-node
	Entrypoint commons = static/js/runtime.js static/css/vendors-node.css static/js/vendors-node.js static/js/commons.js
	Entrypoint app = static/js/runtime.js static/css/vendors-node.css static/js/vendors-node.js static/css/app.css static/js/app.js
	Entrypoint storefront = static/js/runtime.js static/css/vendors-node.css static/js/vendors-node.js static/js/storefront.js

	ERROR in ./src/module/sw-cms/blocks/image/image-three-cover/component/sw-cms-block-image-three-cover.scss (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--15-2!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/module/sw-cms/blocks/image/image-three-cover/component/sw-cms-block-image-three-cover.scss)
	Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
	ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
	Error: ENOENT: no such file or directory, scandir '/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/vendor'
	    at Object.fs.readdirSync (fs.js:904:18)
	    at Object.getInstalledBinaries (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/extensions.js:131:13)
	    at foundBinariesList (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/errors.js:20:15)
	    at foundBinaries (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/errors.js:15:5)
	    at Object.module.exports.missingBinary (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/errors.js:45:5)
	    at module.exports (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/binding.js:15:30)
	    at Object.<anonymous> (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/index.js:14:35)
	    at Module._compile (module.js:653:30)
	    at Object.Module._extensions..js (module.js:664:10)
	    at Module.load (module.js:566:32)
	    at tryModuleLoad (module.js:506:12)
	    at Function.Module._load (module.js:498:3)
	    at Module.require (module.js:597:17)
	    at require (internal/module.js:11:18)
	    at Object.sassLoader (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/sass-loader/lib/loader.js:46:72)
	    at runLoaders (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/webpack/lib/NormalModule.js:313:20)
	    at /Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:367:11
	    at /Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/loader-runner/li/loader.js):\nError: ENOENT: no such file or directory, scandir \'/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/vendor\'\n    at Object.fs.readdirSync (fs.js:904:18)\n    at Object.getInstalledBinaries (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/extensions.js:131:13)\n    at foundBinariesList (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/errors.js:20:15)\n    at foundBinaries (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/errors.js:15:5)\n    at Object.module.exports.missingBinary (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/errors.js:45:5)\n    at module.exports (/Users/sannepeters/shopware/development/platform/src/Administb/LoaderRunner.js:233:18
	    at runSyncOrAsync (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
	    at iterateNormalLoaders (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
	    at Array.<anonymous> (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
	    at Storage.finished (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
	    at provider (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9)
	    at /Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/graceful-fs/graceful-fs.js:115:16
	    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
	 @ ./src/module/sw-cms/blocks/image/image-three-cover/component/sw-cms-block-image-three-cover.scss 4:14-276
	 @ ./src/module/sw-cms/blocks/image/image-three-cover/component/index.js
	 @ ./src/module/sw-cms/blocks/image/image-three-cover/index.js
	 @ ./src/module/sw-cms/blocks/index.js
	 @ ./src/module/sw-cms/index.js
	 @ ./src/module sync \.\/[a-z-]+\/index\.js$
	 @ ./src/module/index.js
	 @ ./src/app/init/modules.init.js
	 @ ./src/app/init/index.js
	 @ ./src/app/main.js

	ERROR in ./src/app/assets/scss/all.scss (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--15-2!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/app/assets/scss/all.scss)
	Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
	ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
	Error: ENOENT: no such file or directory, scandir '/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/vendor'
	    at Object.fs.readdirSync (fs.js:904:18)
	    at Object.getInstalledBinaries (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/extensions.js:131:13)
	    at foundBinariesList (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/errors.js:20:15)
	    at foundBinaries (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/errors.js:15:5)
	    at Object.module.exports.missingBinary (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/errors.js:45:5)
	    at module.exports (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/binding.js:15:30)
	    at Object.<anonymous> (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/index.js:14:35)
	    at Module._compile (module.js:653:30)
	    at Object.Module._extensions..js (module.js:664:10)
	    at Module.load (module.js:566:32)
	    at tryModuleLoad (module.js:506:12)
	    at Function.Module._load (module.js:498:3)
	    at Module.require (module.js:597:17)
	    at require (internal/module.js:11:18)
	    at Object.sassLoader (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/sass-loader/lib/loader.js:46:72)
	    at runLoaders (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/webpack/lib/NormalModule.js:313:20)
	    at /Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:367:11
	    at /Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:233:18
	    at runSyncOrAsync (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
	    at iterateNormalLoaders (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
	    at Array.<anonymousration/Resources/app/administration/node_modules/node-sass/lib/binding.js:15:30)\n    at Object.<anonymous> (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/lib/index.js:14:35)\n    at Module._compile (module.js:653:30)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Module.require (module.js:597:17)\n    at require (internal/module.js:11:18)\n    at Object.sassLoader (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/sass-loader/lib/loader.js:46:72)\n    at runLoaders (/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/webpack/lib/NormalModule.js:313:20)\n`




And then it continues with a lot more ERROR in ... which are similair.

**Comment by SannePetersNL** [comment]
@keulinho keulinho 

When I check the dir in the error message then i indeed do not have that dir. (	Error: ENOENT: no such file or directory, scandir '/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/vendor')

I tried running the whole installer again to fix it but no change.

**Comment by SannePetersNL** [comment]
When I run the normal install script the first error appairs on 28/40 After:

`	# Webpack Plugin Injector: Plugin "Storefront" injected as a new entry point
	Building project for production...
	(node:45279) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
	parseQuery() will be replaced with getOptions() in the next major version of loader-utils.


[ './src/module/sw-cms/elements/image-slider/component/sw-cms-el-image-slider.scss (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--15-2!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/module/sw-cms/elements/image-slider/component/sw-cms-el-image-slider.scss)\nModule build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):\nModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):\nError: ENOENT: no such file or directory, scandir \'/Users/sannepeters/shopware/development/platform/src/Administration/Resources/app/administration/node_modules/node-sass/vendor\'\n    at Object.fs.readdirSync (fs.js:904:18)\n    at Object.getInstalledBinaries (/Users/sannepeters/shopware/development/platform/src/Administration/Resources

`

**Comment by SannePetersNL** [comment]
I removed everything and dropped the database and then followed all the steps again and now it works :D Thanks for the help @keulinho  😄
