### ISSUE TITLE
storefront:hot-proxy spawn xdg-open ENOENT

### ISSUE THREAD

**Issue by tyurderi** [shopware/shopware#343]
**Description**  

When using `storefront:hot-proxy` inside the docker container it results in the following error:
```
	
	############
	Storefront proxy server started at http://localhost:9998
	############
	
	
	events.js:174
	      throw er; // Unhandled 'error' event
	      ^
	
	Error: spawn xdg-open ENOENT
	    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
	    at onErrorNT (internal/child_process.js:415:16)
	    at process._tickCallback (internal/process/next_tick.js:63:19)
	Emitted 'error' event at:
	    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
	    at onErrorNT (internal/child_process.js:415:16)
	    at process._tickCallback (internal/process/next_tick.js:63:19)
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! sw-next-storefront@1.0.0 hot-proxy: `NODE_ENV=development MODE=hot node ./build/start-hot-reload.js`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the sw-next-storefront@1.0.0 hot-proxy script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /var/www/.npm/_logs/2019-12-04T13_46_28_629Z-debug.log
	
Execution aborted, a subcommand failed!
```

**Possible Solution**  

Make https://github.com/shopware/platform/blob/master/src/Storefront/Resources/app/storefront/build/proxy-server-hot/index.js#L69 optional somewhere.

**Additional context**

**Comment by tyurderi** [comment]
Since the associated PR https://github.com/shopware/platform/pull/354 is merged, this issue is solved :)
