### ISSUE TITLE
Promise.all(...).then(...).catch(...).finally is not a function

### ISSUE THREAD

**Issue by LiaraAlis** [shopware/shopware#94]
I got the following error while trying to install:
```
> node vendor/shopware/platform/src/Storefront/Resources/copy-to-vendor.js
        /home/vagrant/shopware-dev/vendor/shopware/platform/src/Storefront/Resources/copy-to-vendor.js:56
                .finally(() => {
                        ^
        
        TypeError: Promise.all(...).then(...).catch(...).finally is not a function
            at onCopyProcess (/home/vagrant/shopware-dev/vendor/shopware/platform/src/Storefront/Resources/copy-to-vendor.js:56:17)
            at Object.<anonymous> (/home/vagrant/shopware-dev/vendor/shopware/platform/src/Storefront/Resources/copy-to-vendor.js:64:1)
            at Module._compile (module.js:652:30)
            at Object.Module._extensions..js (module.js:663:10)
            at Module.load (module.js:565:32)
            at tryModuleLoad (module.js:505:12)
            at Function.Module._load (module.js:497:3)
            at Function.Module.runMain (module.js:693:10)
            at startup (bootstrap_node.js:188:16)
            at bootstrap_node.js:609:3
        
Execution aborted, a subcommand failed!
```

Using npm `6.1.0.1` and node `8.10.0`.

What's going wrong?

**Comment by keulinho** [comment]
Currently you'll need at least node 10 for installing shopware platform.

We will shortly either bring back compatibility for node 8.10 or update our docs for the minimum node version accordingly.

**Comment by LiaraAlis** [comment]
Hi, thanks for the fast reply.

I thought so. But it was not possible for me to bring the things to work with node 10.
I always receive this error: `Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 10.x`
The command `npm rebuild node-sass -force` also had no success. Do you have any idea?

**Comment by keulinho** [comment]
Try to delete your node modules before updating node.

Otherwise node 8 compatibility should be back shortly.

**Comment by LiaraAlis** [comment]
I deleted the `vendor` and `node_modules` directories and tried to install. Now it works.
Thanks for your help. :)
